
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    displayName: 'running unit tests'
    command: test
    projects: 'UnitTests/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
